services:
  sh:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - LLM_API_URL=$OLLAMA_HOST

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app