services:
  sh:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app