services:
  sh:
    build:
      context: .
      dockerfile: Dockerfile
    command: fish
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - NUBANK_USER=$NUBANK_USER
      - NUBANK_PASSWORD=$NUBANK_PASSWORD