services:
  sh:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=$FINAL_BUDGET_OPENAI_API_KEY
      - OLLAMA_HOST=$OLLAMA_HOST

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - .:/app